version: "3"

services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    build: spark/
    depends_on:
      - postgres
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 18080:18080
    links:
      - hive
  postgres:
    image: postgres:13.4-bullseye
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo_catalog
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  hive:
    build: hive/
    entrypoint: ./init.sh
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    links:
      - "postgres:postgres"
